package io.bytescraft.common;

import com.javaquery.util.collection.Collections;
import com.javaquery.util.io.JFile;
import com.javaquery.util.string.Strings;

import java.io.File;
import java.io.FileInputStream;
import java.util.*;

/**
 * Read cURL specific configuration from file.
 * @author javaquery
 * @since 0.0.2
 */
public class Configuration {

    public static final String CURRENT_WORKING_DIR = System.getProperty("user.dir");
    private static final String CONFIG_FILE = "cURL.config";
    private static final List<String> SUPPORTED_CLIENTS = Client.strValues();

    private String collectionName;
    private String collectionDescription;
    private final Set<String> collectionClients;

    public Configuration() {
        collectionClients = new HashSet<>();
        init();
    }

    private void init(){
        JFile configFile = new JFile(CURRENT_WORKING_DIR + File.separatorChar + CONFIG_FILE);
        if (configFile.exists()) {
            try (
                    FileInputStream fileInputStream = new FileInputStream(configFile)
            ) {
                Properties properties = new Properties();
                properties.load(fileInputStream);
                collectionName = properties.getProperty("collection.name");
                collectionDescription = properties.getProperty("collection.description");

                String strCollectionClients = properties.getProperty("collection.clients");
                Strings.nonNullNonEmpty(strCollectionClients, ()->{
                    for (String strClient : strCollectionClients.split("\\|")) {
                        if (SUPPORTED_CLIENTS.contains(strClient)) {
                            collectionClients.add(strClient);
                        }
                    }
                });
            } catch (Exception ignored) {
            }
        }
    }

    public String getCollectionName() {
        return collectionName;
    }

    public String getCollectionDescription() {
        return Strings.nonNullNonEmpty(collectionDescription) ? collectionDescription + "\nAuto generated by cURL(bytescraft.io)": "Collection auto generated by cURL(bytescraft.io) annotation processor.";
    }

    public Set<String> getCollectionClients() {
        if (Collections.nullOrEmpty(collectionClients)) {
            collectionClients.add(Client.POSTMAN.name());
        }
        return collectionClients;
    }
}
